server:
  port: 8059
spring:
  datasource:
    username: zhaochunping
    password: RCTE29s5Bmm4GWu!
    url: jdbc:mysql://8.136.12.248:3306/our_family?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: off
  security:
    user:
      name: leemy
      password: 123
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
logging:
  config: classpath:config/logback.xml